// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: common/v1/enum_notify.proto

package commonv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on NOTIFY with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *NOTIFY) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on NOTIFY with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in NOTIFYMultiError, or nil if none found.
func (m *NOTIFY) ValidateAll() error {
	return m.validate(true)
}

func (m *NOTIFY) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return NOTIFYMultiError(errors)
	}

	return nil
}

// NOTIFYMultiError is an error wrapping multiple validation errors returned by
// NOTIFY.ValidateAll() if the designated constraints aren't met.
type NOTIFYMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m NOTIFYMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m NOTIFYMultiError) AllErrors() []error { return m }

// NOTIFYValidationError is the validation error returned by NOTIFY.Validate if
// the designated constraints aren't met.
type NOTIFYValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e NOTIFYValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e NOTIFYValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e NOTIFYValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e NOTIFYValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e NOTIFYValidationError) ErrorName() string { return "NOTIFYValidationError" }

// Error satisfies the builtin error interface
func (e NOTIFYValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sNOTIFY.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = NOTIFYValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = NOTIFYValidationError{}

// Validate checks the field values on NTF with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *NTF) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on NTF with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in NTFMultiError, or nil if none found.
func (m *NTF) ValidateAll() error {
	return m.validate(true)
}

func (m *NTF) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return NTFMultiError(errors)
	}

	return nil
}

// NTFMultiError is an error wrapping multiple validation errors returned by
// NTF.ValidateAll() if the designated constraints aren't met.
type NTFMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m NTFMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m NTFMultiError) AllErrors() []error { return m }

// NTFValidationError is the validation error returned by NTF.Validate if the
// designated constraints aren't met.
type NTFValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e NTFValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e NTFValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e NTFValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e NTFValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e NTFValidationError) ErrorName() string { return "NTFValidationError" }

// Error satisfies the builtin error interface
func (e NTFValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sNTF.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = NTFValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = NTFValidationError{}
